### ISSUE TITLE
Phase of tag signal

### ISSUE THREAD

**Issue by agnes-yang** [JJJennie4528/RF-Tools#1]
I have read the Java secondary development package. How to detect the phase value of the tag? Do we need special hardware support, or further calculate the data returned by RFID reader in the secondary development package? Can I know the details about this?

**Comment by JingyiNJU** [comment]
Some RFID readers such as Impinj Speedway R420/R220 can detect the phase value. No further calculation is required by using RF-Tools.

**Comment by Agnes-Yang** [comment]
Thanks for you reply!

**Comment by agnes-yang** [comment]
> Some RFID readers such as Impinj Speedway R420/R220 can detect the phase value. No further calculation is required by using RF-Tools.

Thamks for your reply!
